### ISSUE TITLE
item deletion should delete active trades

### ISSUE THREAD

**Issue by cmazuc** [cmazuc/scarfage#11]
ERROR:scarf:Exception on /user/testuser [GET]
Traceback (most recent call last):
  File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./scarf/profile.py", line 94, in show_user_profile
    pd.profileuser.pms()
  File "./scarf/scarflib.py", line 166, in pms
    self.pm_from.append(trademessage(item[0]))
  File "./scarf/scarflib.py", line 548, in __init__
    ti.item = siteitem(item_by_uid(ti.itemid))
  File "./scarf/scarflib.py", line 326, in __init__
    raise NoItem(name)
NoItem: None

**Comment by cmazuc** [comment]
resolved with latest commit
